# Generated by Django 6.1.1 on 2026-09-28 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AulaAcademica',
            fields=[
                ('id_aula', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_aula', models.CharField(max_length=100)),
                ('Nota', models.TextField()),
                ('piso_edificio', models.CharField(max_length=100)),
                ('tipo_aula', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Autoridades',
            fields=[
                ('id_autoridad', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('cedula_identidad', models.CharField(max_length=15, unique=True)),
                ('genero', models.CharField(max_length=50)),
                ('cargo', models.CharField(max_length=100)),
                ('resolucion', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id_bitacora', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=50)),
                ('fecha_hora', models.DateTimeField()),
                ('accion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CalendarioAcademico',
            fields=[
                ('id_calendario_academico', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
                ('descripcion', models.CharField(max_length=150)),
                ('activo', models.BooleanField(default=True)),
                ('tipo', models.CharField(choices=[('PERIODO', 'Período académico'), ('CARGA_NOTAS', 'Carga de notas'), ('NO_LABORABLE', 'No laborable'), ('VACACIONES', 'Vacaciones'), ('INSCRIPCION_TRIMESTRE', 'Inscripción Trimestre'), ('INSCRIPCION_SEMESTRE', 'Inscripción Semestre'), ('ANIVERSARIO', 'Días de aniversarios'), ('GRADUACION', 'Días de graduación'), ('ACTIVIDADES', 'Actividades o operativos')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='EstatusEstudiante',
            fields=[
                ('id_estatus_estudiante', models.AutoField(primary_key=True, serialize=False)),
                ('estatus', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('ingreso', models.CharField(max_length=50)),
                ('descripcion_ingreso', models.CharField(max_length=30)),
                ('fecha_ingreso', models.DateField()),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
                ('perfil_registro', models.CharField(blank=True, choices=[('COORDINADOR_PNF', 'Coordinador de PNF'), ('CONTROL_ESTUDIO', 'Control de Estudio')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id_estudiante', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id_materia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=20)),
                ('recuperacion', models.CharField(max_length=100)),
                ('htea', models.DecimalField(decimal_places=1, max_digits=3)),
                ('htei', models.DecimalField(decimal_places=1, max_digits=3)),
                ('activa', models.BooleanField(default=True)),
                ('tipo_materia', models.CharField(default='Curso', max_length=20)),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
                ('perfil_registro', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('perfil_modificacion', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nucleos',
            fields=[
                ('id_nucleo', models.AutoField(primary_key=True, serialize=False)),
                ('municipio', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PeriodoAcademico',
            fields=[
                ('id_periodo_academico', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pnf',
            fields=[
                ('id_pnf', models.AutoField(primary_key=True, serialize=False)),
                ('pnf', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=60)),
                ('periodo_academico', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SeccionAcademica',
            fields=[
                ('id_seccion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=5)),
                ('turno', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrayectoAcademico',
            fields=[
                ('id_periodo_academico', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('genero', models.CharField(blank=True, max_length=50, null=True)),
                ('cedula_identidad', models.CharField(max_length=15)),
                ('estado_civil', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VerificacionCodigo',
            fields=[
                ('id_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('cedula_identidad', models.CharField(max_length=12)),
                ('token', models.CharField(blank=True, null=True)),
                ('codigo', models.CharField(max_length=10)),
                ('creado', models.DateTimeField()),
                ('intentos', models.PositiveIntegerField(default=0)),
                ('bloqueado_hasta', models.DateTimeField(blank=True, null=True)),
                ('activo', models.IntegerField()),
                ('descripcion', models.CharField(max_length=100)),
                ('fecha_expiracion', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AulaEstudiante',
            fields=[
                ('id_aula_estudiante', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Retiro', 'Retiro'), ('Egreso', 'Egreso'), ('Congelado', 'Congelado'), ('Curso', 'Curso')], default='Curso', max_length=20)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes', to='inicio_sesion.aulaacademica')),
                ('estatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas_estudiante', to='inicio_sesion.estatusestudiante')),
            ],
        ),
        migrations.AddField(
            model_name='estatusestudiante',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estatus', to='inicio_sesion.estudiante'),
        ),
        migrations.CreateModel(
            name='MateriaAsignada',
            fields=[
                ('id_materia_asignada', models.AutoField(primary_key=True, serialize=False)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_suspension', models.DateTimeField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
                ('perfil_registro', models.CharField(blank=True, max_length=50, null=True)),
                ('observacion_registro', models.TextField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('perfil_modificacion', models.CharField(blank=True, max_length=50, null=True)),
                ('observacion_modificacion', models.TextField(blank=True, null=True)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='inicio_sesion.materia')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_materias_modificadas', to='inicio_sesion.usuario')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_materias_registradas', to='inicio_sesion.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='estudiante',
            name='nucleo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.nucleos'),
        ),
        migrations.AddField(
            model_name='aulaacademica',
            name='id_nucleo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to='inicio_sesion.nucleos'),
        ),
        migrations.CreateModel(
            name='CalendarioPeriodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='periodo', to='inicio_sesion.calendarioacademico')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calendarios', to='inicio_sesion.periodoacademico')),
            ],
        ),
        migrations.CreateModel(
            name='PeriodoAcademicoMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodos_academicos', to='inicio_sesion.materia')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias', to='inicio_sesion.periodoacademico')),
            ],
        ),
        migrations.AddField(
            model_name='materia',
            name='id_pnf',
            field=models.ForeignKey(db_column='pnf', on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.pnf'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='pnf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.pnf'),
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id_docente', models.AutoField(primary_key=True, serialize=False)),
                ('activo', models.BooleanField(default=True)),
                ('nucleo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.nucleos')),
                ('pnf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.pnf')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='aulaacademica',
            name='id_pnf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to='inicio_sesion.pnf'),
        ),
        migrations.CreateModel(
            name='PNFNucleo',
            fields=[
                ('id_pnf_nucleo', models.AutoField(primary_key=True, serialize=False)),
                ('id_nucleo', models.ForeignKey(db_column='id_nucleo', on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.nucleos')),
                ('id_pnf', models.ForeignKey(db_column='id_pnf', on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.pnf')),
            ],
        ),
        migrations.AddField(
            model_name='aulaacademica',
            name='id_seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to='inicio_sesion.seccionacademica'),
        ),
        migrations.AddField(
            model_name='materia',
            name='id_trayecto',
            field=models.ForeignKey(db_column='trayecto', on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.trayectoacademico'),
        ),
        migrations.AddField(
            model_name='estatusestudiante',
            name='trayecto',
            field=models.ForeignKey(db_column='trayecto', on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.trayectoacademico'),
        ),
        migrations.CreateModel(
            name='Residencia',
            fields=[
                ('id_residencia', models.AutoField(primary_key=True, serialize=False)),
                ('condicion_residencia', models.CharField(max_length=100)),
                ('municipio', models.CharField(max_length=100)),
                ('parroquia', models.CharField(max_length=100)),
                ('direccion_residencia', models.CharField(max_length=100)),
                ('id_usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='residencia', to='inicio_sesion.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Nacimiento',
            fields=[
                ('id_nacimiento', models.AutoField(primary_key=True, serialize=False)),
                ('pais', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('municipio', models.CharField(max_length=100)),
                ('parroquia', models.CharField(max_length=100)),
                ('direccion_nacimiento', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('id_usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nacimiento', to='inicio_sesion.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='materia',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='materias_modificadas', to='inicio_sesion.usuario'),
        ),
        migrations.AddField(
            model_name='materia',
            name='registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='materias_registradas', to='inicio_sesion.usuario'),
        ),
        migrations.CreateModel(
            name='InformacionSecundaria',
            fields=[
                ('id_secundaria', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_institucion', models.CharField(max_length=100)),
                ('nombre_institucion', models.CharField(max_length=100)),
                ('fecha_grado', models.DateField()),
                ('codigo_sni_opsu', models.CharField(max_length=100, unique=True)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informacion_secundaria', to='inicio_sesion.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialAsignaciones',
            fields=[
                ('id_historial', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_perfil', models.CharField(max_length=50)),
                ('accion', models.CharField(max_length=30)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('nucleo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inicio_sesion.nucleos')),
                ('pnf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inicio_sesion.pnf')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_asignaciones', to='inicio_sesion.usuario')),
            ],
            options={
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.AddField(
            model_name='estudiante',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.usuario'),
        ),
        migrations.AddField(
            model_name='estatusestudiante',
            name='registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estatus_estudiantes_registrados', to='inicio_sesion.usuario'),
        ),
        migrations.CreateModel(
            name='DocumentosEstudiante',
            fields=[
                ('id_documento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_documento', models.CharField(max_length=50)),
                ('archivo', models.FileField(upload_to='documentos_estudiante/')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='inicio_sesion.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='DocenteAsignadoMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('PRINCIPAL', 'Docente Principal'), ('SECUNDARIO', 'Docente Secundario')], max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_suspension', models.DateTimeField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
                ('perfil_registro', models.CharField(blank=True, max_length=50, null=True)),
                ('observacion_registro', models.TextField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('perfil_modificacion', models.CharField(blank=True, max_length=50, null=True)),
                ('observacion_modificacion', models.TextField(blank=True, null=True)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias_asignadas', to='inicio_sesion.docente')),
                ('materia_asignada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docentes', to='inicio_sesion.materiaasignada')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_docentes_modificadas', to='inicio_sesion.usuario')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_docentes_registradas', to='inicio_sesion.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Discapacidad',
            fields=[
                ('id_discapacidad', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_carnet_discapacidad', models.CharField(max_length=50)),
                ('nro_registro_medico', models.CharField(max_length=5)),
                ('tipo_discapacidad', models.CharField(max_length=20)),
                ('grado_discapacidad', models.CharField(max_length=50)),
                ('causa_discapacidad', models.CharField(max_length=50)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discapacidades', to='inicio_sesion.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='DirectorGeneral',
            fields=[
                ('id_director', models.AutoField(primary_key=True, serialize=False)),
                ('nucleo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directores_generales', to='inicio_sesion.nucleos')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controles_estudio', to='inicio_sesion.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='DatosPreofesion',
            fields=[
                ('id_dato_academico', models.AutoField(primary_key=True, serialize=False)),
                ('profesion_pregrado', models.CharField(max_length=150)),
                ('universidad_egreso_pregrado', models.CharField(max_length=150)),
                ('pais_profesion_pregrado', models.CharField(max_length=150)),
                ('id_usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='id_profesional', to='inicio_sesion.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id_cuenta', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=160, unique=True)),
                ('clave', models.CharField(max_length=160)),
                ('tipo_cuenta', models.CharField(choices=[('ADMIN', 'Administrativo'), ('EST', 'Estudiante')], max_length=20)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuenta', to='inicio_sesion.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='CoordinadorPNF',
            fields=[
                ('id_coordinador', models.AutoField(primary_key=True, serialize=False)),
                ('activo', models.BooleanField(default=True)),
                ('nucleo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.nucleos')),
                ('pnf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.pnf')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ControlEstudio',
            fields=[
                ('id_control', models.AutoField(primary_key=True, serialize=False)),
                ('activo', models.BooleanField(default=True)),
                ('nucleo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias_asignadas', to='inicio_sesion.nucleos')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docentes', to='inicio_sesion.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ContactoAuxiliar',
            fields=[
                ('id_representante', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('cedula_identidad', models.CharField(max_length=15)),
                ('telefono', models.CharField(max_length=15)),
                ('parentesco', models.CharField(max_length=25)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos_auxiliares', to='inicio_sesion.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id_contacto', models.AutoField(primary_key=True, serialize=False)),
                ('telefono_suplete', models.CharField(blank=True, max_length=15, null=True)),
                ('telefono_personal', models.CharField(max_length=15)),
                ('correo_electronico', models.EmailField(max_length=100, unique=True)),
                ('correo_alternativo', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('id_usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contacto', to='inicio_sesion.usuario')),
            ],
        ),
        migrations.AddConstraint(
            model_name='estudiante',
            constraint=models.UniqueConstraint(fields=('usuario', 'nucleo', 'pnf'), name='uq_estudiante_usuario_nucleo_pnf'),
        ),
        migrations.AddConstraint(
            model_name='docenteasignadomateria',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True), ('rol', 'PRINCIPAL')), fields=('materia_asignada',), name='uq_docente_principal_activo'),
        ),
        migrations.AddConstraint(
            model_name='docenteasignadomateria',
            constraint=models.UniqueConstraint(condition=models.Q(('rol', 'SECUNDARIO')), fields=('materia_asignada',), name='uq_docente_secundario'),
        ),
        migrations.AddConstraint(
            model_name='docente',
            constraint=models.UniqueConstraint(fields=('usuario', 'nucleo', 'pnf'), name='uq_docente_usuario_nucleo_pnf'),
        ),
        migrations.AddConstraint(
            model_name='directorgeneral',
            constraint=models.UniqueConstraint(fields=('usuario', 'nucleo'), name='uq_director_usuario'),
        ),
        migrations.AddConstraint(
            model_name='coordinadorpnf',
            constraint=models.UniqueConstraint(fields=('usuario', 'nucleo', 'pnf'), name='uq_coordinadorpnf_usuario_nucleo_pnf'),
        ),
        migrations.AddConstraint(
            model_name='controlestudio',
            constraint=models.UniqueConstraint(fields=('usuario', 'nucleo'), name='uq_control_usuario_nucleo'),
        ),
    ]
