# Generated by Django 6.0.3 on 2026-08-28 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio_sesion', '0002_datos_iniciales'),
    ]

    operations = [
        migrations.AddField(
            model_name='seccionacademica',
            name='turno',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
