# Generated by Django 6.1.1 on 2026-09-28 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio_sesion', '0002_datos_iniciales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlestudio',
            name='nucleo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controles_estudio', to='inicio_sesion.nucleos'),
        ),
        migrations.AlterField(
            model_name='controlestudio',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controles_estudio', to='inicio_sesion.usuario'),
        ),
        migrations.AlterField(
            model_name='directorgeneral',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directores_generales', to='inicio_sesion.usuario'),
        ),
    ]
