# Generated by Django 6.0.3 on 2026-08-29 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio_sesion', '0003_seccionacademica_turno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aulaestudiante',
            name='estatus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas_estudiante', to='inicio_sesion.estatusestudiante'),
        ),
    ]
