# Generated by Django 6.0.3 on 2026-08-29 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio_sesion', '0004_alter_aulaestudiante_estatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aulaestudiante',
            name='estado',
            field=models.CharField(choices=[('Retiro', 'Retiro'), ('Egreso', 'Egreso'), ('Congelado', 'Congelado'), ('Curso', 'Curso')], default='Curso', max_length=20),
        ),
        migrations.AlterField(
            model_name='aulaestudiante',
            name='fecha_final',
            field=models.DateField(blank=True, null=True),
        ),
    ]
