# Generated by Django 6.0.3 on 2026-09-03 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio_sesion', '0005_alter_aulaestudiante_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estatusestudiante',
            name='condicion_inicial',
            field=models.CharField(blank=True, choices=[('NO_APLICA', 'No aplica'), ('APROBADO', 'Inicial aprobado'), ('PENDIENTE', 'Debe presentar Inicial'), ('REPROBADO', 'Inicial reprobado')], default='NO_APLICA', max_length=20, null=True),
        ),
    ]
