# Generated by Django 6.0.3 on 2026-09-03 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio_sesion', '0006_estatusestudiante_condicion_inicial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estatusestudiante',
            name='condicion_inicial',
        ),
    ]
