# Generated by Django 6.0.3 on 2027-07-19 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio_sesion', '0007_remove_estatusestudiante_condicion_inicial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='tipo_materia',
            field=models.CharField(blank=True, default='Curso', max_length=20, null=True),
        ),
    ]
