# Generated by Django 6.0.3 on 2026-08-28 13:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inicio_sesion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetallePlanificacion',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('titulo_unidad', models.CharField(max_length=255)),
                ('ponderacion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('contenido_unidad', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Calificaciones',
            fields=[
                ('id_calificaciones', models.AutoField(primary_key=True, serialize=False)),
                ('promedio_tramo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('asistencia', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('condicion', models.CharField(max_length=100)),
                ('fecha_promedio', models.DateField()),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calificaciones', to='inicio_sesion.estudiante')),
                ('materia_asignada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calificaciones', to='inicio_sesion.materiaasignada')),
                ('trayecto', models.ForeignKey(db_column='trayecto', on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.trayectoacademico')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleEvaluacion',
            fields=[
                ('id_evaluacion', models.AutoField(primary_key=True, serialize=False)),
                ('metodo_evaluacion', models.CharField(max_length=100)),
                ('porcentaje_evaluacion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_evaluacion', models.DateField()),
                ('detalle_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='notas_academicas.detalleplanificacion')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCalificacionesUnidad',
            fields=[
                ('id_detalle_calificaciones_unidad', models.AutoField(primary_key=True, serialize=False)),
                ('nota_unidad', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_calificacion', models.DateField(auto_now_add=True)),
                ('calificacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_unidad', to='notas_academicas.calificaciones')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calificaciones_unidad', to='notas_academicas.detalleplanificacion')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialModificacionNotas',
            fields=[
                ('id_historial', models.AutoField(primary_key=True, serialize=False)),
                ('trayecto', models.CharField(max_length=50)),
                ('fecha_modificacion', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.TextField()),
                ('docente_asignado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inicio_sesion.docenteasignadomateria')),
                ('periodo_academico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inicio_sesion.periodoacademico')),
                ('usuario_modifica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inicio_sesion.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialDetalleNota',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('numero_unidad', models.PositiveSmallIntegerField()),
                ('nota_anterior', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nota_nueva', models.DecimalField(decimal_places=2, max_digits=5)),
                ('asistencia_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('asistencia_nueva', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('promedio_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('promedio_nuevo', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inicio_sesion.estudiante')),
                ('historial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='notas_academicas.historialmodificacionnotas')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialTrayectoEstudiante',
            fields=[
                ('id_historial', models.AutoField(primary_key=True, serialize=False)),
                ('anio', models.PositiveIntegerField()),
                ('trayecto_anterior', models.CharField(max_length=20)),
                ('trayecto_nuevo', models.CharField(max_length=20)),
                ('cantidad_materias', models.PositiveSmallIntegerField()),
                ('materias_reprobadas', models.PositiveSmallIntegerField()),
                ('materias_mala_asistencia', models.PositiveSmallIntegerField()),
                ('estado', models.CharField(max_length=50)),
                ('puede_pasar', models.BooleanField(default=False)),
                ('motivo', models.TextField()),
                ('fecha_procesamiento', models.DateTimeField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historiales_trayecto', to='inicio_sesion.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='PlanificacionAcademica',
            fields=[
                ('id_planificacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('estado_aceptacion', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADO', 'Enviado al Coordinador'), ('ACEPTADA', 'Aceptada'), ('DENEGADA', 'Denegada')], default='BORRADOR', max_length=10)),
                ('materia_asignacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inicio_sesion.materiaasignada')),
                ('nucleo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inicio_sesion.nucleos')),
                ('periodo_academico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inicio_sesion.periodoacademico')),
                ('pnf', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inicio_sesion.pnf')),
            ],
        ),
        migrations.AddField(
            model_name='detalleplanificacion',
            name='plan_academico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='notas_academicas.planificacionacademica'),
        ),
        migrations.AddField(
            model_name='calificaciones',
            name='periodo_materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calificaciones', to='notas_academicas.planificacionacademica'),
        ),
        migrations.CreateModel(
            name='PromedioFinal',
            fields=[
                ('id_promedio_final', models.AutoField(primary_key=True, serialize=False)),
                ('promedio_final', models.DecimalField(decimal_places=2, max_digits=5)),
                ('estado', models.CharField(max_length=100)),
                ('fecha_promedio', models.DateField()),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promedios_finales', to='inicio_sesion.estudiante')),
                ('materia_asignacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promedios_finales', to='inicio_sesion.materiaasignada')),
                ('trayecto', models.ForeignKey(db_column='trayecto', on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.trayectoacademico')),
            ],
        ),
    ]
