# Generated by Django 6.1.1 on 2026-09-28 02:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inicio_sesion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificaciones',
            fields=[
                ('id_calificaciones', models.AutoField(primary_key=True, serialize=False)),
                ('promedio_tramo', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('asistencia', models.PositiveSmallIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('condicion', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_promedio', models.DateField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
                ('perfil_registro', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('perfil_modificacion', models.CharField(blank=True, max_length=50, null=True)),
                ('congelada', models.BooleanField(default=False)),
                ('fecha_congelacion', models.DateTimeField(blank=True, null=True)),
                ('estudiante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calificaciones_estudiante', to='inicio_sesion.estudiante')),
                ('materia_asignada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calificaciones_materia', to='inicio_sesion.materiaasignada')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calificaciones_modificadas', to='inicio_sesion.usuario')),
                ('periodo_materia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calificaciones_periodo', to='inicio_sesion.periodoacademicomateria')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calificaciones_registradas', to='inicio_sesion.usuario')),
                ('trayecto', models.ForeignKey(blank=True, db_column='trayecto', null=True, on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.trayectoacademico')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePlanificacion',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('titulo_unidad', models.CharField(max_length=255)),
                ('ponderacion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('contenido_unidad', models.TextField()),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificado', models.DateTimeField(blank=True, null=True)),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalles_planificacion_modificados', to='inicio_sesion.usuario')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalles_planificacion_registrados', to='inicio_sesion.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleEvaluacion',
            fields=[
                ('id_evaluacion', models.AutoField(primary_key=True, serialize=False)),
                ('metodo_evaluacion', models.TextField()),
                ('porcentaje_evaluacion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_evaluacion', models.DateField()),
                ('detalle_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='notas_academicas.detalleplanificacion')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCalificacionesUnidad',
            fields=[
                ('id_detalle_calificaciones_unidad', models.AutoField(primary_key=True, serialize=False)),
                ('nota_unidad', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_calificacion', models.DateField(auto_now_add=True)),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
                ('perfil_registro', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('perfil_modificacion', models.CharField(blank=True, max_length=50, null=True)),
                ('congelada', models.BooleanField(default=False)),
                ('fecha_congelacion', models.DateTimeField(blank=True, null=True)),
                ('calificacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_unidad', to='notas_academicas.calificaciones')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalles_calificaciones_modificados', to='inicio_sesion.usuario')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalles_calificaciones_registrados', to='inicio_sesion.usuario')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calificaciones_unidad', to='notas_academicas.detalleplanificacion')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluacionReparacion',
            fields=[
                ('id_evaluacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('materia_asignacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evaluaciones_reparacion_materia', to='inicio_sesion.materiaasignada')),
                ('nucleo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evaluaciones_reparacion_nucleo', to='inicio_sesion.nucleos')),
                ('pnf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evaluaciones_reparacion_pnf', to='inicio_sesion.pnf')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleEvaluacionReparacion',
            fields=[
                ('id_detalle_reparacion', models.AutoField(primary_key=True, serialize=False)),
                ('porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tipo_evaluacion', models.CharField(choices=[('EXAMEN', 'Examen'), ('INFORME', 'Informe'), ('PROYECTO', 'Proyecto'), ('EXPOSICION', 'Exposición'), ('PRACTICA', 'Práctica'), ('CUESTIONARIO', 'Cuestionario'), ('PROGRAMACION', 'Desarrollo de Programa'), ('DIAGRAMA_FLUJO', 'Diagrama de Flujo'), ('OTRO', 'Otro')], default='OTRO', max_length=50)),
                ('evaluacion_reparacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='notas_academicas.evaluacionreparacion')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialModificacionNotas',
            fields=[
                ('id_historial', models.AutoField(primary_key=True, serialize=False)),
                ('perfil_modificacion', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('tipo_modificacion', models.CharField(choices=[('MODIFICACION', 'Modificación'), ('REVERSION', 'Reversión')], default='MODIFICACION', max_length=20)),
                ('calificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='historial_modificaciones', to='notas_academicas.calificaciones')),
                ('docente_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='historial_modificaciones_notas', to='inicio_sesion.docenteasignadomateria')),
                ('periodo_academico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='historial_modificaciones_notas', to='inicio_sesion.periodoacademico')),
                ('trayecto', models.ForeignKey(blank=True, db_column='trayecto', null=True, on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.trayectoacademico')),
                ('usuario_modifica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial_modificaciones_notas', to='inicio_sesion.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialDetalleNota',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('nota_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('nota_nueva', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('asistencia_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('asistencia_nueva', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('promedio_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('promedio_nuevo', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('detalle_calificacion_unidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='historial_modificaciones', to='notas_academicas.detallecalificacionesunidad')),
                ('estudiante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='historial_detalles_notas', to='inicio_sesion.estudiante')),
                ('historial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='notas_academicas.historialmodificacionnotas')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialTrayectoEstudiante',
            fields=[
                ('id_historial', models.AutoField(primary_key=True, serialize=False)),
                ('anio', models.PositiveIntegerField()),
                ('cantidad_materias', models.PositiveSmallIntegerField()),
                ('materias_reprobadas', models.PositiveSmallIntegerField()),
                ('materias_mala_asistencia', models.PositiveSmallIntegerField()),
                ('estado', models.CharField(max_length=50)),
                ('puede_pasar', models.BooleanField(default=False)),
                ('motivo', models.TextField()),
                ('fecha_procesamiento', models.DateTimeField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historiales_trayecto', to='inicio_sesion.estudiante')),
                ('trayecto_anterior', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historiales_trayecto_anterior', to='inicio_sesion.trayectoacademico')),
                ('trayecto_nuevo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historiales_trayecto_nuevo', to='inicio_sesion.trayectoacademico')),
            ],
        ),
        migrations.CreateModel(
            name='ModificacionReparacion',
            fields=[
                ('id_modificacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_modificacion', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.CharField(default='Modificación de nota de reparación', max_length=255)),
                ('evaluacion_reparacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modificaciones', to='notas_academicas.evaluacionreparacion')),
            ],
        ),
        migrations.CreateModel(
            name='PlanificacionAcademica',
            fields=[
                ('id_planificacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('estado_aceptacion', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADO', 'Enviado al Coordinador'), ('ACEPTADA', 'Aceptada'), ('DENEGADA', 'Denegada')], default='BORRADOR', max_length=10)),
                ('materia_asignacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planificaciones_academicas', to='inicio_sesion.materiaasignada')),
                ('nucleo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inicio_sesion.nucleos')),
                ('periodo_academico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inicio_sesion.periodoacademico')),
                ('pnf', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inicio_sesion.pnf')),
            ],
        ),
        migrations.AddField(
            model_name='detalleplanificacion',
            name='plan_academico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='notas_academicas.planificacionacademica'),
        ),
        migrations.AddField(
            model_name='calificaciones',
            name='planificacion_academica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calificaciones_planificacion', to='notas_academicas.planificacionacademica'),
        ),
        migrations.CreateModel(
            name='PromedioFinal',
            fields=[
                ('id_promedio_final', models.AutoField(primary_key=True, serialize=False)),
                ('promedio_final', models.DecimalField(decimal_places=2, max_digits=5)),
                ('asistencia', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('estado', models.CharField(max_length=100)),
                ('fecha_promedio', models.DateField()),
                ('motivo', models.TextField(blank=True, null=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promedios_finales', to='inicio_sesion.estudiante')),
                ('materia_asignacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promedios_finales', to='inicio_sesion.materiaasignada')),
                ('trayecto', models.ForeignKey(db_column='trayecto', on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.trayectoacademico')),
            ],
        ),
        migrations.CreateModel(
            name='Reparacion',
            fields=[
                ('id_reparacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_reparacion', models.DateField(blank=True, null=True)),
                ('calificacion', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('estado', models.CharField(blank=True, choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('REPROBADO', 'Reprobado')], default='PENDIENTE', max_length=20, null=True)),
                ('estudiante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reparaciones', to='inicio_sesion.estudiante')),
                ('evaluacion_reparacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reparaciones', to='notas_academicas.evaluacionreparacion')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleModificacionReparacion',
            fields=[
                ('id_detalle_modificacion', models.AutoField(primary_key=True, serialize=False)),
                ('nota_anterior', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('nota_nueva', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('estado_anterior', models.CharField(blank=True, max_length=20, null=True)),
                ('estado_nuevo', models.CharField(blank=True, max_length=20, null=True)),
                ('modificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='notas_academicas.modificacionreparacion')),
                ('reparacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial_modificaciones', to='notas_academicas.reparacion')),
            ],
        ),
    ]
