# Generated by Django 6.0.3 on 2026-09-07 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio_sesion', '0005_alter_aulaestudiante_estado_and_more'),
        ('notas_academicas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planificacionacademica',
            name='materia_asignacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planificaciones_academicas', to='inicio_sesion.materiaasignada'),
        ),
    ]
