# Generated by Django 6.0.3 on 2026-11-23 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio_sesion', '0005_alter_aulaestudiante_estado_and_more'),
        ('notas_academicas', '0002_alter_planificacionacademica_materia_asignacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialmodificacionnotas',
            name='trayecto',
            field=models.ForeignKey(blank=True, db_column='trayecto', null=True, on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.trayectoacademico'),
        ),
        migrations.AlterField(
            model_name='historialtrayectoestudiante',
            name='trayecto_anterior',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historiales_trayecto_anterior', to='inicio_sesion.trayectoacademico'),
        ),
        migrations.AlterField(
            model_name='historialtrayectoestudiante',
            name='trayecto_nuevo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historiales_trayecto_nuevo', to='inicio_sesion.trayectoacademico'),
        ),
    ]
