# Generated by Django 6.0.3 on 2026-11-23 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas_academicas', '0003_alter_historialmodificacionnotas_trayecto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialdetallenota',
            name='nota_anterior',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='historialdetallenota',
            name='nota_nueva',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
