# Generated by Django 6.0.3 on 2026-11-23 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas_academicas', '0004_alter_historialdetallenota_nota_anterior_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialdetallenota',
            name='numero_unidad',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
