# Generated by Django 6.0.3 on 2026-09-03 03:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio_sesion', '0005_alter_aulaestudiante_estado_and_more'),
        ('notas_academicas', '0005_alter_historialdetallenota_numero_unidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificaciones',
            name='planificacion_academica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calificaciones_planificacion', to='notas_academicas.planificacionacademica'),
        ),
        migrations.AlterField(
            model_name='calificaciones',
            name='asistencia',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='calificaciones',
            name='condicion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='calificaciones',
            name='estudiante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calificaciones_estudiante', to='inicio_sesion.estudiante'),
        ),
        migrations.AlterField(
            model_name='calificaciones',
            name='fecha_promedio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calificaciones',
            name='materia_asignada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calificaciones_materia', to='inicio_sesion.materiaasignada'),
        ),
        migrations.AlterField(
            model_name='calificaciones',
            name='periodo_materia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calificaciones_periodo', to='inicio_sesion.periodoacademicomateria'),
        ),
        migrations.AlterField(
            model_name='calificaciones',
            name='promedio_tramo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='calificaciones',
            name='trayecto',
            field=models.ForeignKey(blank=True, db_column='trayecto', null=True, on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.trayectoacademico'),
        ),
    ]
