# Generated by Django 6.0.3 on 2026-09-03 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas_academicas', '0006_calificaciones_planificacion_academica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promediofinal',
            name='motivo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
