# Generated by Django 6.0.3 on 2026-09-06 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas_academicas', '0007_promediofinal_motivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='promediofinal',
            name='asistencia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
