# Generated by Django 6.0.3 on 2026-09-06 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio_sesion', '0008_materia_tipo_materia'),
        ('notas_academicas', '0008_promediofinal_asistencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionReparacion',
            fields=[
                ('id_evaluacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('materia_asignacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evaluaciones_reparacion_materia', to='inicio_sesion.materiaasignada')),
                ('nucleo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evaluaciones_reparacion_nucleo', to='inicio_sesion.nucleos')),
                ('pnf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evaluaciones_reparacion_pnf', to='inicio_sesion.pnf')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleEvaluacionReparacion',
            fields=[
                ('id_detalle_reparacion', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('puntaje_maximo', models.DecimalField(decimal_places=2, default=20, max_digits=5)),
                ('tipo_evaluacion', models.CharField(choices=[('EXAMEN', 'Examen'), ('INFORME', 'Informe'), ('PROYECTO', 'Proyecto'), ('EXPOSICION', 'Exposición'), ('PRACTICA', 'Práctica'), ('CUESTIONARIO', 'Cuestionario'), ('PROGRAMACION', 'Desarrollo de Programa'), ('DIAGRAMA_FLUJO', 'Diagrama de Flujo'), ('OTRO', 'Otro')], default='OTRO', max_length=50)),
                ('evaluacion_reparacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='notas_academicas.evaluacionreparacion')),
            ],
        ),
        migrations.CreateModel(
            name='Reparacion',
            fields=[
                ('id_reparacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_reparacion', models.DateField(blank=True, null=True)),
                ('calificacion', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('estudiante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reparaciones', to='inicio_sesion.estudiante')),
                ('evaluacion_reparacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reparaciones', to='notas_academicas.evaluacionreparacion')),
                ('materia_asignacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reparaciones', to='inicio_sesion.materiaasignada')),
                ('trayecto', models.ForeignKey(blank=True, db_column='trayecto', null=True, on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.trayectoacademico')),
            ],
        ),
        migrations.CreateModel(
            name='CalificacionReparacion',
            fields=[
                ('id_calificacion', models.AutoField(primary_key=True, serialize=False)),
                ('nota_obtenida', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('detalle_evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calificaciones', to='notas_academicas.detalleevaluacionreparacion')),
                ('reparacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='notas_academicas.reparacion')),
            ],
        ),
    ]
