# Generated by Django 6.0.3 on 2026-09-07 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas_academicas', '0009_evaluacionreparacion_detalleevaluacionreparacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleevaluacionreparacion',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='detalleevaluacionreparacion',
            name='puntaje_maximo',
        ),
        migrations.RemoveField(
            model_name='evaluacionreparacion',
            name='observacion',
        ),
        migrations.RemoveField(
            model_name='reparacion',
            name='materia_asignacion',
        ),
        migrations.RemoveField(
            model_name='reparacion',
            name='trayecto',
        ),
        migrations.AddField(
            model_name='reparacion',
            name='estado',
            field=models.CharField(blank=True, choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('REPROBADO', 'Reprobado')], default='PENDIENTE', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='reparacion',
            name='calificacion',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
    ]
