# Generated by Django 6.0.3 on 2027-12-01 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio_sesion', '0008_materia_tipo_materia'),
        ('notas_academicas', '0010_remove_detalleevaluacionreparacion_descripcion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModificacionReparacion',
            fields=[
                ('id_modificacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_modificacion', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.CharField(default='Modificación de nota de reparación', max_length=255)),
                ('evaluacion_reparacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modificaciones', to='notas_academicas.evaluacionreparacion')),
                ('usuario_modifica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modificaciones_reparacion', to='inicio_sesion.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleModificacionReparacion',
            fields=[
                ('id_detalle_modificacion', models.AutoField(primary_key=True, serialize=False)),
                ('nota_anterior', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('nota_nueva', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('estado_anterior', models.CharField(blank=True, max_length=20, null=True)),
                ('estado_nuevo', models.CharField(blank=True, max_length=20, null=True)),
                ('reparacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial_modificaciones', to='notas_academicas.reparacion')),
                ('modificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='notas_academicas.modificacionreparacion')),
            ],
        ),
    ]
