# Generated by Django 6.0.3 on 2027-12-01 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notas_academicas', '0011_modificacionreparacion_detallemodificacionreparacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modificacionreparacion',
            name='usuario_modifica',
        ),
    ]
