# Generated by Django 6.0.3 on 2026-09-07 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notas_academicas', '0012_remove_modificacionreparacion_usuario_modifica'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CalificacionReparacion',
        ),
    ]
